name: Build Product Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-product-service:
    name: Build product service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Adjust as needed
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-product-${{ hashFiles('product/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-product-
      - name: Build Product service
        run: cd product && mvn clean install package -Dmaven.test.skip=true -U